### ISSUE TITLE
Access bmtk NetCon object instead of creating new one for low level neurons

### ISSUE THREAD

**Issue by MJC598** [vinayguntu/LUT_Prelim#13]
Instead of creating two NetCon objects, we need to utilize the bmtk NetCon they have. This could be causing #12 and could help fix the spike issue. Also corresponding to [TODO](https://github.com/vinayguntu/LUT_Prelim/blob/master/feedback_loop.py#L170).

**Comment by chenziao** [comment]
In bmtk, the [record_spike module](https://github.com/AllenInstitute/bmtk/blob/6f868d9f8476e3d334cb3f8bac70809818a0fbc8/bmtk/simulator/bionet/biosimulator.py#L190) is doing the same thing as in our feedbackloop module. It resets the recording vector in every [block](https://github.com/AllenInstitute/bmtk/blob/develop/bmtk/simulator/bionet/modules/record_spikes.py#L92) since the vector seems not to continue to record after being read.
I checked by using the netcon created in feedbackloop module to record spikes, then the vectors for spike recording created by bmtk is no longer recording. The reason is given in the [Neuron doc](https://neuron.yale.edu/neuron/static/new_doc/modelspec/programmatic/network/netcon.html?highlight=netcon#NetCon.record). "NB: Recording takes place on a per source, not a per netcon basis, and the source only records into one vector at a time..." "The source will continue to record events until record is called with another netcon connecting to the source ...".
So using "tvec = sim._spikes[gid]" in [here](https://github.com/vinayguntu/LUT_Prelim/blob/4_22_feedbackloop/feedback_loop.py#L46) should fix this issue.

**Comment by MJC598** [comment]
@chenziao so does this mean that we can remove the [resetting of the old netcon?](https://github.com/vinayguntu/LUT_Prelim/blob/4_22_feedbackloop/feedback_loop.py#L312) Also I believe I ran this and [these](https://github.com/vinayguntu/LUT_Prelim/tree/4_22_feedbackloop/images/4_23SetSpikeDetector) are the graphs produced. Does this fix your primary concern @vinayguntu ?

**Comment by chenziao** [comment]
> @chenziao so does this mean that we can remove the [resetting of the old netcon?](https://github.com/vinayguntu/LUT_Prelim/blob/4_22_feedbackloop/feedback_loop.py#L312) Also I believe I ran this and [these](https://github.com/vinayguntu/LUT_Prelim/tree/4_22_feedbackloop/images/4_23SetSpikeDetector) are the graphs produced. Does this fix your primary concern @vinayguntu ?

Reset should be done every time when the block is called. The vectors for the spike record module are refreshed in each block, meaning the vectors used for previous block will be thrown away. If not resetting the vectors in feedbackloop, it will hold only the vectors for the first block, and not continue to recording new spikes.

**Comment by MJC598** [comment]
Closed via #17
